/**
 * Music Teacher — song catalog + multi-lens analyses.
 * Shared by Song Lab and Circle of Fifths.
 */
window.MusicTeacher = window.MusicTeacher || {};

MusicTeacher.MAJORS = ["C", "G", "D", "A", "E", "B", "F#", "Db", "Ab", "Eb", "Bb", "F"];
MusicTeacher.MINORS = ["Am", "Em", "Bm", "F#m", "C#m", "G#m", "Ebm", "Bbm", "Fm", "Cm", "Gm", "Dm"];

MusicTeacher.ALIASES = {
  "C#": "Db", "Gb": "F#", "G#": "Ab", "D#": "Eb", "A#": "Bb",
  "A#m": "Bbm", "D#m": "Ebm", "Abm": "G#m", "Dbm": "C#m", "Gbm": "F#m",
};

MusicTeacher.LENSES = [
  { id: "pitch", name: "Pitch & harmony", short: "Pitch", hint: "Key, mode, chords, circle path" },
  { id: "melody", name: "Melody", short: "Melody", hint: "Contour, motifs, chord tones" },
  { id: "rhythm", name: "Rhythm & time", short: "Rhythm", hint: "Tempo, meter, groove, accents" },
  { id: "articulation", name: "Articulation", short: "Articulation", hint: "Staccato, legato, mute, attack" },
  { id: "form", name: "Form & structure", short: "Form", hint: "Sections and overall design" },
  { id: "texture", name: "Texture", short: "Texture", hint: "Who plays what, density" },
  { id: "dynamics", name: "Dynamics", short: "Dynamics", hint: "Where intensity moves" },
  { id: "timbre", name: "Timbre & gear", short: "Timbre", hint: "Tone, amp, pedals, mix" },
  { id: "technique", name: "Technique", short: "Technique", hint: "How it is physically played" },
  { id: "lyrics", name: "Lyrics & meaning", short: "Lyrics", hint: "Story and word-setting" },
  { id: "style", name: "Style & context", short: "Style", hint: "Genre, era, references" },
  { id: "effect", name: "Effect on you", short: "Effect", hint: "Emotional arc and hooks" },
];

MusicTeacher.SONGS = {
  over_the_mountain: {
    title: "Over the Mountain",
    artist: "Ozzy Osbourne · Diary of a Madman (1981)",
    tonic: "G#m",
    mode: "G♯ Aeolian (natural minor)",
    blurb: "Concert key G♯ minor (E♭ tuning). The emotional engine is the Aeolian metal cadence VI–VII–i.",
    youtube: "https://www.youtube.com/watch?v=YwWVE84OEIA",
    lenses: {
      pitch: "Home is G♯ Aeolian. Verse i→IV (G♯m→C♯) brightens briefly; chorus E–F♯–G♯m is VI–VII–i — the classic Aeolian lift-and-fall. Bridge walks C♯m–B–A (left on the circle).",
      melody: "Vocal is chant-like over the minor pedal; Rhoads solo lines mix minor pentatonic, blues, and raised-6th Dorian color while staying G♯-centered.",
      rhythm: "~140 BPM feel, straight rock drive. Palm-muted intro sets a locked pulse before verse opens.",
      articulation: "Palm-muted riff attack in the intro; double-stop pull-offs; heavier sustained chorus lift.",
      form: "Intro riff → verse → chorus → bridge → solo → resolve. Compact verse–chorus metal with a classical-tinged bridge color.",
      texture: "Rhythm guitar + bass lock the pedal; vocal sits on top; solo guitar takes the lead in the break.",
      dynamics: "Riff punch → verse grind → chorus lift → bridge shade → solo peak → tonic collapse.",
      timbre: "Early-80s Ozzy / Rhoads: saturated guitar, clear vocal, dry-to-room rock production.",
      technique: "Palm mute, pull-offs, power-chord shapes; solo uses pentatonic/blues phrasing with neoclassical flashes.",
      lyrics: "Astral escape and freedom — leaving the ground for the mountain beyond.",
      style: "Rhoads-era heavy metal with classical guitar vocabulary inside a rock song form.",
      effect: "Lift on the chorus (VI–VII) then inevitable return home — yearning that never quite escapes G♯ minor.",
    },
    sections: [
      { id: "intro", name: "Intro / main riff", keys: ["G#m"], chords: "G♯m pedal", function: "i — tonic gravity", note: "Palm-muted root and double-stop pull-offs lock the ear on G♯ minor before the verse opens." },
      { id: "verse", name: "Verse", keys: ["G#m", "Db"], chords: "G♯m → C♯", function: "i → IV", note: "Dark tonic pedal with a bright IV lift. Heavy chant-like vocal over the minor home." },
      { id: "chorus", name: "Chorus", keys: ["E", "F#", "G#m"], chords: "E → F♯ → (G♯m)", function: "VI → VII → i", note: "Relative-major lift (E / F♯) then the classic Aeolian return to G♯m — the song’s lift-and-fall." },
      { id: "bridge", name: "Bridge", keys: ["C#m", "B", "A"], chords: "C♯m → B → A", function: "iv → III → II♭ color", note: "Steps left on the circle: parallel minor of IV, then III, then an open A-major color before home." },
      { id: "solo", name: "Guitar solo", keys: ["G#m"], chords: "G♯ minor language", function: "i — pentatonic / Dorian color", note: "Still centered on G♯ minor: pentatonic, blues, and occasional raised 6th (Dorian) in the Rhoads lines." },
      { id: "resolve", name: "Resolve / close", keys: ["G#m"], chords: "G♯m", function: "i — home", note: "Everything collapses back onto the tonic. The circle journey ends where it began." },
    ],
    teach: [
      { title: "Plant the home", keys: ["G#m"], teach: "Find G♯m on the inner ring. That’s home. The song’s advantage: everything else will feel like a trip away from — or back to — this one wedge." },
      { title: "Verse: one step of brightness", keys: ["G#m", "Db"], teach: "Verse adds C♯ (spelled Db on the wheel) — the IV of G♯m. On the circle, IV sits next door (counterclockwise from the relative-major side). Tiny move, big lift without leaving the neighborhood." },
      { title: "Chorus: the Aeolian triangle", keys: ["E", "F#", "G#m"], teach: "E → F♯ → G♯m is VI → VII → i. Look: E and F♯ sit beside G♯m’s relative-major family. The song takes advantage of short circle hops for a huge emotional lift-then-fall — yearning that always lands home." },
      { title: "Bridge: walk left", keys: ["C#m", "B", "A"], teach: "Bridge steps further around: C♯m–B–A. That’s using the circle as a path, not just a home — shade and color before the solo snaps back to G♯m." },
      { title: "What it takes advantage of", keys: ["E", "F#", "G#m"], teach: "Takeaway: Over the Mountain lives on a tight Aeolian cluster. It doesn’t modulate far — it weaponizes neighbors for lift (VI–VII) and gravity (back to i)." },
    ],
  },
  diary_of_a_madman: {
    title: "Diary of a Madman",
    artist: "Ozzy Osbourne · Diary of a Madman (1981)",
    tonic: "G#m",
    mode: "G♯ minor with Dorian, diminished & Hungarian colors",
    blurb: "Same tonic world as Over the Mountain, but the harmony wanders farther — altered cells, parallel shades, and exotic minor in the solo.",
    youtube: "https://www.youtube.com/watch?v=YwWVE84OEIA",
    lenses: {
      pitch: "G♯ minor home with diminished/#11 approaches, iv color (C♯m), remote E♭m shade, and Hungarian/Gypsy minor (harmonic minor + raised 4th) in the solo.",
      melody: "Classical-inspired intro cells; vocal mantra on the hook; solo melodic language flips from exotic Hungarian intervals to minor pentatonic exit.",
      rhythm: "Odd meters (~7/8 verses, ~6/8 hook) — form as instability. Compound feel on the refrain.",
      articulation: "Clean fingered intro vs band-hard riff; soft interlude touch vs aggressive solo articulation.",
      form: "Suite-like: classical intro → odd-meter riff → verses → hook → soft interlude → Hungarian solo → final hooks. Maps madness as structure.",
      texture: "Solo classical guitar opening; full band metal; intimate “dear diary” room; then virtuosic lead.",
      dynamics: "Fragile → stalking → mantra → whisper → blaze → resignation.",
      timbre: "Nylon/classical color into high-gain Rhoads lead; production frames the suite contrasts.",
      technique: "Classical fingerstyle → metal rhythm → Hungarian-minor runs and pentatonic exits.",
      lyrics: "Madness as diary entries — confession, obsession, collapse.",
      style: "Neoclassical metal suite; Brouwer-adjacent classical guitar meets Ozzy vocal theater.",
      effect: "Unease that never fully resolves — the tonic accepts the madness rather than curing it.",
    },
    sections: [
      { id: "intro", name: "Clean intro", keys: ["G#m"], chords: "altered / dim → G♯m", function: "Unstable approach to i", note: "Classical, uncanny harmony (#11, dim7, add9) with gravity toward G♯ minor — Brouwer-inspired opening." },
      { id: "riff", name: "Odd-meter riff", keys: ["G#m"], chords: "G♯-minor world", function: "i — compressed classical material", note: "Band enters; the classical cells harden into a stalking G♯-minor metal frame." },
      { id: "verse", name: "Verses (~7/8)", keys: ["G#m", "C#m"], chords: "G♯7♯11 → G♯dim7 → C♯m6", function: "altered i → iv color", note: "Diminished and extended minor cells keep the tonic uneasy rather than settled." },
      { id: "hook", name: "Hook / refrain (~6/8)", keys: ["G#m"], chords: "G♯ minor mantra", function: "i — compound feel", note: "“Diary of a madman…” swings harder over the same minor center — form as obsession." },
      { id: "interlude", name: "Soft interlude", keys: ["Ebm"], chords: "~D♯m / related minor", function: "remote minor shade", note: "Fragile “dear diary” room: fingered Emadd9 world sounding near D♯ minor — a step away on the circle." },
      { id: "solo", name: "Solo (Hungarian minor)", keys: ["G#m"], chords: "G♯ Hungarian / Gypsy minor", function: "i — exotic tonic", note: "Harmonic minor + raised 4th over G♯, then exits into minor pentatonic. Same home, different scale color." },
      { id: "close", name: "Final hooks / close", keys: ["G#m"], chords: "G♯m refrain", function: "i — resignation", note: "Return to the refrain world. The circle doesn’t escape — it accepts the tonic." },
    ],
    teach: [
      { title: "Same home as Over the Mountain", keys: ["G#m"], teach: "Diary stays on G♯m — same wedge as Over the Mountain. Advantage: one tonic world for the whole album suite, so madness is scale-color and form, not a new key." },
      { title: "Unstable approaches to i", keys: ["G#m", "C#m"], teach: "Verses lean toward C♯m (iv) with diminished/#11 cells. On the circle you’re still next to home — tension without leaving the block." },
      { title: "The soft room: one step away", keys: ["Ebm"], teach: "Interlude sits near E♭m / D♯m — a neighbor shade on the wheel. Fragile “dear diary” moment = circle adjacency used as intimacy, not a big modulation." },
      { title: "Hungarian solo: same wedge, new color", keys: ["G#m"], teach: "Solo stays on G♯m but flips to Hungarian/Gypsy minor (raised 4th). Circle lesson: you can change the paint without moving the house." },
      { title: "What it takes advantage of", keys: ["G#m", "C#m", "Ebm"], teach: "Takeaway: Diary uses the circle for small escapes (iv, remote minor shade) then refuses to leave G♯m — obsession mapped as geography." },
    ],
  },
  mr_crowley: {
    title: "Mr. Crowley",
    artist: "Ozzy Osbourne · Blizzard of Ozz (1980) · Randy Rhoads",
    tonic: "Dm",
    mode: "D Aeolian / D harmonic minor — same tonal pattern as Diary, easier key",
    blurb: "RR comparison: classical intro → minor home → Aeolian i–VII–VI (Dm–C–B♭), same chord family as Diary’s E–F♯–G♯m, just rotated and in friendlier D minor.",
    youtube: null,
    lenses: {
      pitch: "D Aeolian with classical V (A). Verse Dm–C–B♭ = i–VII–VI — same triangle as Diary’s VI–VII–i, easier spelling. Chorus adds III (F) brightness.",
      melody: "Organ/classical doorway; vocal sits in D minor; Rhoads solo uses harmonic-minor leading tones and neoclassical runs.",
      rhythm: "Straight mid-tempo metal pulse; classical intro freer; solo section drives harder.",
      articulation: "Organ sustain → heavy palm/power chords → legato neoclassical solo lines.",
      form: "Organ intro → verse → chorus → solo → outro with V↔i closure — clearer classical cadences than Diary.",
      texture: "Organ + band; vocal center; written Rhoads solo as featured voice.",
      dynamics: "Gothic open → heavy verse/chorus → virtuosic peak → classical close.",
      timbre: "Pipe/organ color into saturated RR guitar; occult theater in the mix.",
      technique: "Classical cadences, harmonic-minor runs, trills, diminished tension into V→i.",
      lyrics: "Address to Aleister Crowley — occult narrator questioning the magician.",
      style: "Neoclassical metal prototype; Rhoads classical vocabulary in rock form.",
      effect: "Same Aeolian family as Diary, but friendlier D minor with clearer resolve — easier ear training key.",
    },
    sections: [
      { id: "intro", name: "Organ / classical intro", keys: ["Dm", "A"], chords: "Dm → A", function: "i → V", note: "Gothic organ opens on D minor with a classical V pull (A) — same “classical doorway into metal” architecture as Diary’s clean intro." },
      { id: "verse", name: "Verse", keys: ["Dm", "C", "Bb"], chords: "Dm → C → B♭", function: "i → VII → VI", note: "Same Aeolian three-chord engine as Diary. Diary spells it VI–VII–i (E–F♯–G♯m); Crowley starts on the tonic: i–VII–VI (Dm–C–B♭). Identical triangle on the circle." },
      { id: "chorus", name: "Chorus / heavy", keys: ["Dm", "Bb", "F", "C"], chords: "Dm · B♭ · F · C", function: "i → VI → III → VII", note: "Stays in the D-minor neighborhood: relative major F (III) brightens, then C (VII) leans back toward home." },
      { id: "solo", name: "Main solo", keys: ["Dm"], chords: "D minor / harmonic minor", function: "i — neoclassical language", note: "Rhoads written solo over D minor: pentatonic, harmonic-minor leading tones, classical runs — Diary’s Hungarian color is a spicier cousin of this toolkit." },
      { id: "outro", name: "Outro solo / close", keys: ["Dm", "A"], chords: "Dm · A · classical runs", function: "i ↔ V — resolve", note: "Trills, diminished tension, and V→i closure. Crowley uses the easier D-minor home with clearer classical cadences." },
    ],
    teach: [
      { title: "Rotate the triangle to D minor", keys: ["Dm"], teach: "Find Dm on the inner ring. Same Aeolian engine as Diary/Over the Mountain — just rotated to an easier key. That’s the teaching trick: patterns move around the wheel." },
      { title: "Classical V doorway", keys: ["Dm", "A"], teach: "Intro uses A major as V of Dm — clockwise neighbor on the major ring above. Classical music’s favorite short hop: i↔V." },
      { title: "Verse: i–VII–VI triangle", keys: ["Dm", "C", "Bb"], teach: "Dm–C–B♭. Compare to Diary’s E–F♯–G♯m (VI–VII–i). Same three-chord triangle on the circle — Crowley starts on tonic and walks down; Diary hits the lift then home." },
      { title: "Chorus adds relative major", keys: ["Dm", "Bb", "F", "C"], teach: "F (III) is Dm’s relative major — outer ring, same slice. Brightens without leaving the neighborhood." },
      { title: "What it takes advantage of", keys: ["Dm", "C", "Bb", "A"], teach: "Takeaway: Crowley proves the Aeolian triangle is portable. Same circle shape as Diary, friendlier spelling, plus clear V→i cadences for classical closure." },
    ],
  },
  the_trooper: {
    title: "The Trooper",
    artist: "Iron Maiden · Piece of Mind (1983) · Steve Harris",
    tonic: "Em",
    mode: "E Aeolian — gallop metal; twin leads; brief Am solo shift",
    blurb: "E-minor cavalry charge: VI–VII–i neighborhood like Diary/Crowley, driven by gallop rhythm and harmonized leads rather than classical V→i.",
    youtube: "https://www.youtube.com/watch?v=X4bgXH3sJ2Q",
    lenses: {
      pitch: "E Aeolian. Chorus D–C–Em is VII–VI–i (same triangle family). Solo 2 relocates the machine to Am (iv of Em).",
      melody: "Twin-lead theme in 3rds is the hook; Dickinson vocal narrative over gallop; solos blues/pentatonic then Am-world trills.",
      rhythm: "Harris gallop (eighth + two sixteenths) is the song’s character — cavalry as rhythm. Momentum over chord change.",
      articulation: "Martial twin-lead fanfare; gallop palm/pick attack; sustained chorus chords; solo bends and trills.",
      form: "Intro theme → gallop verse → chorus lift → dual solos (Em then Am) → final verse/outro home.",
      texture: "Twin guitars (Murray/Smith), gallop bass as engine, vocal as battlefield report.",
      dynamics: "Fanfare → charge → anthem lift → solo chaos → smoke of tonic close.",
      timbre: "NWOBHM twin-lead bite; bright Marshall-ish crunch; live war-theater energy.",
      technique: "Harmonized leads, alternate-picked gallop, bends, whammy chaos in solo 2.",
      lyrics: "Crimean War cavalry charge (Tennyson echo) — first-person soldier in the fog.",
      style: "NWOBHM signature; Thin Lizzy twin-lead DNA; war poetry as metal program music.",
      effect: "Forward motion you can’t stop — the gallop *is* the story.",
    },
    sections: [
      { id: "intro", name: "Intro / twin-lead theme", keys: ["Em"], chords: "E minor melody (harmonized)", function: "i — thematic fanfare", note: "Murray + Smith open in E Aeolian, often in 3rds. The lead *is* the riff — martial fanfare before the gallop locks in." },
      { id: "verse", name: "Verse (gallop)", keys: ["Em"], chords: "Em / E5 pedal", function: "i — charge engine", note: "Harris gallop over E-minor home. Momentum over chord changes — cavalry as rhythm." },
      { id: "chorus", name: "Chorus / lift", keys: ["D", "C", "Em", "G"], chords: "D → C → Em (G color)", function: "VII → VI → i (III)", note: "Same Aeolian triangle as Diary/Crowley: D–C–Em is VII–VI–i in E minor. G (III) flashes relative-major brightness." },
      { id: "solo1", name: "Solo 1 (Adrian Smith)", keys: ["Em", "D", "Bm", "C"], chords: "E5–D5–B5–C5–D5", function: "i – VII – v – VI – VII", note: "E minor blues/pentatonic over the Aeolian loop. Bends and descending licks — rock voice on the Em battlefield." },
      { id: "solo2", name: "Solo 2 (Dave Murray)", keys: ["Am", "G", "Em", "F"], chords: "A5–G5–Em–F–G", function: "shift to Am (iv area)", note: "Same Aeolian machine relocated to A minor (iv of Em). Trills, bends, whammy — chaos before the charge returns home." },
      { id: "outro", name: "Final verse / outro", keys: ["Em"], chords: "Em theme + gallop", function: "i — return", note: "Harmony theme and gallop snap back to E minor. No happy cadence — the charge ends in the tonic’s smoke." },
    ],
    teach: [
      { title: "Home: E minor", keys: ["Em"], teach: "Em on the inner ring. Maiden’s charge lives here. Advantage of the circle: keep harmony simple so rhythm (gallop) and twin leads can be the drama." },
      { title: "Chorus: same triangle, new key", keys: ["D", "C", "Em", "G"], teach: "D–C–Em is VII–VI–i in E minor — identical family to Crowley/Diary. G (III) flashes relative-major brightness (outer ring above Em)." },
      { title: "Solo 2: move the machine", keys: ["Am", "G", "Em", "F"], teach: "Same Aeolian loop relocated to Am (iv of Em). On the wheel, Am sits near Em’s neighborhood — a short move that feels like chaos without changing the song’s DNA." },
      { title: "What it takes advantage of", keys: ["D", "C", "Em"], teach: "Takeaway: Trooper uses the circle for portable chord engines. Gallop + twin leads carry the story; harmony stays on short circle hops so the cavalry never loses the road." },
    ],
  },
  aces_high: {
    title: "Aces High",
    artist: "Iron Maiden · Powerslave (1984) · Steve Harris",
    tonic: "Em",
    mode: "E Aeolian with mobile i–VI–VII — solos Am → Bm",
    blurb: "Full makeup: staccato/palm-muted twin-lead scramble → legato verse flow; gallop; Em Aeolian with key-hopping i–VI–VII; dual solos Am→Bm.",
    youtube: "https://www.youtube.com/watch?v=Xg9aQvjMS60",
    lenses: {
      pitch: "E Aeolian home; Em–C–D = i–VI–VII. Solos hop Am (iv) then Bm (v) — whole-step climb of the same machine.",
      melody: "Twin-lead scramble cells; Dickinson anthem chorus; Murray legato streams vs Smith mixed blues/picked bite.",
      rhythm: "Gallop engine throughout; intro cells are rhythmically tight; chorus uses longest held values.",
      articulation: "KEY LESSON: intro = staccato/palm-muted detached attack (alarm); verse = legato/connected flow (flight narrative); chorus = tenuto/held (anthem).",
      form: "Staccato intro → legato verse → pre-chorus climb → sustained chorus → Am break → dual solos → restated close.",
      texture: "Twin leads as sirens; gallop bass; vocal as pilot; dual-solo contrast as two aces.",
      dynamics: "Alarm scramble → narrative flow → anthem slam → solo climb → landing.",
      timbre: "Marshall crunch, TS-style mid boost for leads, delay on solos; WWII theater production energy.",
      technique: "Palm mute, twin harmony, gallop picking, hammer/pull legato (Murray), blues + chromatic snaps (Smith).",
      lyrics: "Battle of Britain pilot POV — scramble, climb, live to fly / fly to live.",
      style: "NWOBHM war anthem; Churchill/BoB context; Powerslave-era Maiden peak.",
      effect: "Articulation tells the story: choppy alarm → connected flight → held triumph.",
    },
    sections: [
      { id: "intro", name: "Intro / scramble (staccato)", keys: ["F#m", "Am", "Em"], chords: "harmonized 6-note cells + fast riff 2", function: "i–VI–VII takeoff · detached attack", note: "Light palm mute = staccato/percussive twin leads. Notes are short, separated, machine-gun articulated — scramble alarm before sustained singing tone arrives." },
      { id: "verse", name: "Verse (legato shift)", keys: ["Em", "D", "C"], chords: "moving power chords under vocal", function: "i + VII/VI · connected phrasing", note: "Articulation flips: freer sustain/legato chord motion and vocal line vs intro’s chop. Gallop still drives, but phrases connect instead of spit." },
      { id: "prechorus", name: "Pre-chorus / bridge 1", keys: ["Em", "C", "D"], chords: "repeating lick → split harmonies", function: "tension climb", note: "Tighter picked figures, then twin-lead split again — reintroduces harmonic bite before the held chorus chords." },
      { id: "chorus", name: "Chorus (“Live to fly…”)", keys: ["Em", "C", "D", "G"], chords: "held power chords Em–C–D → G lift", function: "i–VI–VII · sustained", note: "Longest note values in the song: slammed, sustained chords under Dickinson’s anthem. Articulation = tenuto/held, opposite of intro staccato." },
      { id: "break", name: "Break / solo launch", keys: ["Am"], chords: "A-minor riff (tricky rhythm)", function: "iv staging", note: "Percussive A-minor bed resets articulation toward attack again — runway for Murray’s legato solo voice." },
      { id: "solo1", name: "Solo 1 (Murray · legato)", keys: ["Am"], chords: "Am pentatonic over Am bed", function: "iv · fluid lead", note: "Murray’s signature hammer/pull legato: connected streams vs Smith’s more picked bite. Articulation contrast between the two aces." },
      { id: "solo2", name: "Solo 2 (Smith · mixed)", keys: ["Bm"], chords: "Bm (+ blues ♭5 / Dorian 6)", function: "v · whole-step climb", note: "Legato runs + blues licks + short staccato chromatic snaps — mixes detached and smooth inside one solo." },
      { id: "outro", name: "Final verse / chorus / riff", keys: ["Em", "C", "D"], chords: "return to Em–C–D world", function: "i — land", note: "Restates verse legato narrative + sustained chorus, then riff energy — full articulation arc closes." },
    ],
    teach: [
      { title: "Same Em home as Trooper", keys: ["Em"], teach: "Aces High shares Em with The Trooper. Circle advantage: one NWOBHM home key; difference is how they travel and articulate." },
      { title: "i–VI–VII scramble", keys: ["Em", "C", "D"], teach: "Em–C–D = i–VI–VII. C and D are Em’s close major neighbors on the wheel — the flight path stays local so staccato intro can feel urgent without harmonic confusion." },
      { title: "Chorus holds the same path", keys: ["Em", "C", "D", "G"], teach: "Chorus uses the same circle path but with long held chords (+ G lift). Advantage: identical geography, new articulation = new meaning (alarm → anthem)." },
      { title: "Solos climb the circle", keys: ["Am", "Bm"], teach: "Solo 1 on Am (iv), Solo 2 on Bm (v). Whole-step climb around the minor ring — same machine, rising battlefield." },
      { title: "What it takes advantage of", keys: ["Em", "C", "D", "Am", "Bm"], teach: "Takeaway: Aces High shows the circle as a runway. Short hops for the song body; iv→v climb for solo drama; articulation does the storytelling on top of that map." },
    ],
  },
  mozart_k581: {
    title: "Clarinet Quintet in A, K. 581",
    artist: "W. A. Mozart (1789)",
    tonic: "A",
    mode: "A major (Ionian), with parallel Aeolian contrast",
    blurb: "Classical tonic–dominant–subdominant geography around A. Parallel A minor is shade, not a remote modulation.",
    youtube: null,
    lenses: {
      pitch: "A Ionian home. Dominant E (V), subdominant D (IV), parallel Am (Aeolian) as intimate shade — local circle journey.",
      melody: "Clarinet cantabile themes; aria-like Larghetto; variation writing in the finale.",
      rhythm: "Classical meters: Allegro common time, Larghetto 3/4, Menuetto/Trio dance, Theme & variations.",
      articulation: "Classical bow/clarinet articulation — legato singing lines vs Menuetto lift; Trio I more intimate.",
      form: "Four movements: sonata Allegro → Larghetto → Menuetto with two Trios → Theme & variations close.",
      texture: "Clarinet + string quartet; Trio I often strings alone; clarinet glow returns in Trio II.",
      dynamics: "Classical terraced and nuanced dynamics; intimate shade in Am, glow in A major.",
      timbre: "Clarinet in A — warm, blended with strings; A major chosen for instrument color.",
      technique: "Classical sonata, variation, and dance forms; clarinet cantabile technique.",
      lyrics: "Instrumental — meaning lives in mode contrast and form.",
      style: "High Classical chamber music; modal contrast (Ionian/Aeolian) as expressive tool.",
      effect: "Sunlit A major with sudden intimate Am shadow — same letter, flipped mode.",
    },
    sections: [
      { id: "allegro", name: "I. Allegro", keys: ["A", "E"], chords: "A major · 2nd theme → E", function: "I → V (sonata)", note: "Exposition sits in A; the second theme often leans to the dominant E — classic rightward move on the circle." },
      { id: "larghetto", name: "II. Larghetto", keys: ["D"], chords: "D major", function: "IV — subdominant", note: "Warm leftward step to the subdominant. Aria-like 3/4 contrast to the bright A home." },
      { id: "menuetto", name: "III. Menuetto", keys: ["A"], chords: "A major", function: "I", note: "Minuet returns to tonic A; the form frames the two trios." },
      { id: "trio1", name: "III. Trio I", keys: ["Am"], chords: "A minor", function: "i — parallel Aeolian", note: "Same tonic letter, flipped mode. Strings alone — intimate shadow on the inner ring." },
      { id: "trio2", name: "III. Trio II", keys: ["A"], chords: "A major", function: "I — clarinet glow", note: "Back to Ionian; clarinet solos over the strings in the home major." },
      { id: "theme", name: "IV. Theme", keys: ["A", "E"], chords: "A → E → A", function: "I ↔ V", note: "Theme phrases walk tonic to dominant and back — the shortest path on the circle." },
      { id: "var3", name: "IV. Variation III", keys: ["Am"], chords: "A minor", function: "i — parallel shade", note: "Viola-led variation flips to Aeolian again before the major close." },
      { id: "close", name: "IV. Close", keys: ["A"], chords: "A major", function: "I — Adagio → Allegro", note: "Final return to A major. The circle’s journey is local: A, E, D, and parallel Am." },
    ],
    teach: [
      { title: "Home: A major (outer ring)", keys: ["A"], teach: "Mozart starts on the major ring — A. Classical music’s home base uses the circle differently than metal: I–V–IV geography, not Aeolian triangles." },
      { title: "Dominant: one step clockwise", keys: ["A", "E"], teach: "Allegro second theme leans to E (V). Clockwise = up a fifth. The shortest, strongest classical move on the wheel." },
      { title: "Subdominant: one step left", keys: ["D"], teach: "Larghetto sits in D (IV) — counterclockwise. Warmth and rest without remote keys." },
      { title: "Parallel shade: flip the mode", keys: ["Am"], teach: "Trio I / Var. III flip to Am — same slice, inner ring. Not a far modulation: parallel Aeolian as intimate shadow." },
      { title: "What it takes advantage of", keys: ["A", "E", "D", "Am"], teach: "Takeaway: Mozart uses the circle’s closest neighbors only (I, V, IV, parallel i). Maximum clarity — contrast by mode and movement, not distant travel." },
    ],
  },
};
